service: serverless-example

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-northeast-2
  stage: ${opt:stage, 'dev'}
  ecr:
    images:
      cicd_repository:
        platform: linux/amd64
        path: ./

functions:
  api:
    architecture: arm64
    image:
      name: mbti-backend
      command:
        - dist/main.handler
      entryPoint:
        - '/main-entrypoint.sh'
    events:
      - http:
          method: any
          path: /{any+}
