name: Deploy to Lambda

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'ECR Image Tag'
        required: true
permissions:
  id-token: write

env:
  AWS_LAMBDA_FUNCTION_NAME: mbti_backend
  AWS_LAMBDA_IMAGE_URI: ${{secrets.AWS_ECR_REPOSITORY_URL}}:${{ github.event.inputs.image }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ap-northeast-2
      - name: AWS Lambda Deploy
        run: |
          aws lambda update-function-code --function-name $AWS_LAMBDA_FUNCTION_NAME --image-uri $AWS_LAMBDA_IMAGE_URI --publish
