name: Deploy to Lambda

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'ECR Image Tag'
        required: true
permissions:
  id-token: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-2
          description: 'Deploy from GitHub Actions'
          dry_run: true
          image_uri: ${{secrets.AWS_ECR_REPOSITORY_URL}}:${{ github.event.inputs.image }}
          function_name: mbti_backend
