name: Deploy to Lambda

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'ECR Image Tag'
        required: true
permissions:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_LAMBDA_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ap-northeast-2
      - name: AWS Lambda Deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_region: ap-northeast-2
          description: 'Deploy from GitHub Actions'
          dry_run: true
          image_uri: ${{secrets.AWS_ECR_REPOSITORY_URL}}:${{ github.event.inputs.image }}
          function_name: mbti_backend
