name: Test Before Merge
on:
  pull_request:
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
      - run: cd backend && npm ci && npm run build --if-present && npm test
